export enum AppRoles {
  /**
   * @UserModule
   */
  ADMIN_CREATE_ANY_USER = 'ADMIN_CREATE_ANY_USER',
  ADMIN_READ_ANY_USER = 'ADMIN_READ_ANY_USER',
  ADMIN_UPDATE_ANY_USER = 'ADMIN_UPDATE_ANY_USER',
  ADMIN_DELETE_ANY_USER = 'ADMIN_DELETE_ANY_USER',
  MODERATOR_UPDATE_OWN_USER = 'MODERATOR_UPDATE_OWN_USER',
  MODERATOR_READ_OWN_USER = 'MODERATOR_READ_OWN_USER',

  /**
   * @CategoryModule
   */
  ADMIN_CREATE_ANY_CATEGORY = 'ADMIN_CREATE_ANY_CATEGORY',
  ADMIN_READ_ANY_CATEGORY = 'ADMIN_READ_ANY_CATEGORY',
  ADMIN_UPDATE_ANY_CATEGORY = 'ADMIN_UPDATE_ANY_CATEGORY',
  ADMIN_DELETE_ANY_CATEGORY = 'ADMIN_DELETE_ANY_CATEGORY',
  MODERATOR_CREATE_ANY_CATEGORY = 'MODERATOR_CREATE_ANY_CATEGORY',
  MODERATOR_READ_ANY_CATEGORY = 'MODERATOR_READ_ANY_CATEGORY',
  MODERATOR_UPDATE_OWN_CATEGORY = 'MODERATOR_UPDATE_OWN_CATEGORY',
  MODERATOR_DELETE_OWN_CATEGORY = 'MODERATOR_DELETE_OWN_CATEGORY',

  /**
   * @TagModule
   */
  ADMIN_CREATE_ANY_TAG = 'ADMIN_CREATE_ANY_TAG',
  ADMIN_READ_ANY_TAG = 'ADMIN_READ_ANY_TAG',
  ADMIN_UPDATE_ANY_TAG = 'ADMIN_UPDATE_ANY_TAG',
  ADMIN_DELETE_ANY_TAG = 'ADMIN_DELETE_ANY_TAG',
  MODERATOR_CREATE_ANY_TAG = 'MODERATOR_CREATE_ANY_TAG',
  MODERATOR_READ_ANY_TAG = 'MODERATOR_READ_ANY_TAG',
  MODERATOR_UPDATE_OWN_TAG = 'MODERATOR_UPDATE_OWN_TAG',
  MODERATOR_DELETE_OWN_TAG = 'MODERATOR_DELETE_OWN_TAG',
}
